[package]
name = "three-commas-scraper"
version = "0.0.0"
authors = ["Aleksander Heintz <alxandr@alxandr.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-std = { version = "1", features = ["attributes"] }
async-trait = "0.1"
clap = "3.0.0-beta.2"
chrono = { version = "0.4", features = ["serde"] }
crossbeam = "0.8"
futures = "0.3"
hex = "0.4"
indexmap = "1"
prometheus = "0.12"
rust_decimal = "1"
tide = { version = "0.16", default-features = false, features = ["h1-server"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.2"

three-commas-client = { path = "../client" }
three-commas-types = { path = "../types" }
