[package]
name = "three-commas-scraper"
version = "0.0.0"
authors = ["Aleksander Heintz <alxandr@alxandr.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.45"
async-std = { version = "1.10.0", features = ["attributes"] }
async-trait = "0.1.51"
chrono = { version = "0.4.19", features = ["serde"] }
clap = "3.0.0-beta.2"
crossbeam = "0.8.1"
futures = "0.3.18"
hex = "0.4.3"
im = "15.0.0"
prometheus = "0.13.0"
rust_decimal = "1.17.0"
tide = { version = "0.16.0", default-features = false, features = [
  "h1-server",
] }
tracing = "0.1.29"
tracing-futures = "0.2.5"
tracing-subscriber = "0.2.25"

three-commas-client = { version = "0.0.0", path = "../client" }
three-commas-types = { version = "0.0.0", path = "../types" }
